name: gpt_integration
description: 'TradingView integration w/ GPT 4o API'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: 1.2.1
  workmanager: 0.5.2
  flutter_native_splash: ^2.3.9
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash/logo.png
  android_12:
    image: assets/images/splash/logo.png
  android: true
  ios: true
  web: false
